"use client";

import React, { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { getSavedReports, generateCustomBrief, saveAIReport } from "@/lib/api";
import { EconomicSignalsBanner } from "@/components/EconomicSignalsBanner";
import { Skeleton } from "@/components/ui/skeleton";
import { 
  BookOpen, 
  Calendar, 
  AlertCircle, 
  Sparkles, 
  Download, 
  BookmarkPlus, 
  CheckCircle, 
  Scale, 
  ShieldAlert, 
  TrendingUp,
  FileText,
  Printer
} from "lucide-react";

const BRIEF_TOPICS = [
  "Macro Diagnostic & Structural Outlook",
  "Inflation, Food Security & Monetary Tightening",
  "Exchange Rate Dynamics & External Reserves",
  "Public Debt Sustainability & Fiscal Space",
  "Labor Markets, Poverty & Demographic Dividends",
];

export default function ResearchHub() {
  const queryClient = useQueryClient();
  const [selectedTopic, setSelectedTopic] = useState(BRIEF_TOPICS[0]);
  const [activeBrief, setActiveBrief] = useState<any>(null);
  const [saveSuccess, setSaveSuccess] = useState(false);

  // Fetch saved research reports
  const { data: reports, isLoading: reportsLoading, isError: reportsError } = useQuery({
    queryKey: ["saved_reports"],
    queryFn: getSavedReports,
  });

  // Mutation to generate a new grounded brief
  const generateMutation = useMutation({
    mutationFn: (topic: string) => generateCustomBrief(topic),
    onSuccess: (data) => {
      if (data?.report) {
        setActiveBrief(data.report);
        setSaveSuccess(false);
      }
    },
  });

  // Mutation to save active brief
  const saveMutation = useMutation({
    mutationFn: (report: any) => {
      return saveAIReport({
        title: report.title,
        summary: report.summary,
        insights: report.key_insights || [],
        outlook: report.outlook || "Moderate",
        risk_factors: report.risk_factors || [],
      });
    },
    onSuccess: () => {
      setSaveSuccess(true);
      queryClient.invalidateQueries({ queryKey: ["saved_reports"] });
    },
  });

  const handleExportMarkdown = (report: any) => {
    const mdContent = `# ${report.title}
**Topic:** ${report.topic || "Macroeconomic Brief"}
**Outlook:** ${report.outlook || "Evaluated"}
**Pulse Baseline:** ${report.pulse_score ? `${report.pulse_score}/100` : "N/A"}

## Executive Summary
${report.summary}

## Key Insights
${(report.key_insights || report.insights || []).map((ins: string) => `- ${ins}`).join("\n")}

## Policy Recommendations
${(report.policy_recommendations || []).map((rec: string) => `- ${rec}`).join("\n")}

## Downside Risk Factors
${(report.risk_factors || []).map((risk: string) => `- ${risk}`).join("\n")}

---
*Generated by EconoNigeria Open Economic Intelligence Infrastructure (https://econonigeria.org)*
`;

    const blob = new Blob([mdContent], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `EconoNigeria-Brief-${(report.topic || "macro").toLowerCase().replace(/\s+/g, "-")}.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const getOutlookBadge = (outlook: string = "") => {
    const lower = outlook.toLowerCase();
    if (lower.includes("resilient") || lower.includes("expansion") || lower.includes("positive")) {
      return "bg-emerald-600 text-white";
    }
    if (lower.includes("vulnerable") || lower.includes("stress") || lower.includes("critical") || lower.includes("negative")) {
      return "bg-destructive text-destructive-foreground";
    }
    return "bg-amber-500 text-white dark:bg-amber-600";
  };

  return (
    <div className="space-y-12">
      {/* Header */}
      <div className="border-b-4 border-foreground pb-6">
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
          <div>
            <div className="font-mono text-xs uppercase tracking-widest text-muted-foreground mb-2">
              Phase C Intelligence Engine
            </div>
            <h1 className="text-4xl md:text-5xl font-bold tracking-tight uppercase">
              Research Hub & Policy Briefs
            </h1>
            <p className="text-lg text-muted-foreground mt-3 font-serif italic max-w-3xl">
              Strictly grounded macroeconomic analyses, anomaly detection signals, and policy syntheses compiled directly from verified central bank, bureau of statistics, and multilateral datasets.
            </p>
          </div>
          <div className="flex items-center gap-2">
            <span className="px-3 py-1 bg-foreground text-background font-mono text-xs font-bold uppercase tracking-wider">
              Zero Hallucination
            </span>
          </div>
        </div>
      </div>

      {/* Real-time Economic Signals Surveillance */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h2 className="text-sm font-mono font-bold uppercase tracking-widest text-foreground flex items-center gap-2">
            <ShieldAlert className="w-4 h-4 text-foreground" />
            Active Signal Surveillance
          </h2>
        </div>
        <EconomicSignalsBanner />
      </div>

      {/* Grounded AI Policy Brief Generator */}
      <div className="border-4 border-foreground bg-background p-6 space-y-6">
        <div className="border-b-2 border-foreground pb-4 flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-foreground" />
              <h2 className="text-xl font-bold uppercase tracking-tight">
                Synthesize Grounded Policy Brief
              </h2>
            </div>
            <p className="text-sm font-serif text-muted-foreground mt-1">
              Select an analytical angle. The engine compiles verified metrics, pulse drivers, and signals before Gemini synthesizes the brief.
            </p>
          </div>

          <button
            onClick={() => generateMutation.mutate(selectedTopic)}
            disabled={generateMutation.isPending}
            className="px-5 py-2.5 bg-foreground text-background font-mono text-xs font-bold uppercase tracking-widest hover:bg-muted-foreground transition-colors disabled:opacity-50 shrink-0"
          >
            {generateMutation.isPending ? "Grounding in Data..." : "Generate Brief"}
          </button>
        </div>

        {/* Topic Selector */}
        <div className="flex flex-wrap gap-2">
          {BRIEF_TOPICS.map((topic) => (
            <button
              key={topic}
              onClick={() => setSelectedTopic(topic)}
              className={`px-3 py-1.5 text-xs font-mono uppercase tracking-wider border transition-colors ${
                selectedTopic === topic
                  ? "bg-foreground text-background border-foreground font-bold"
                  : "bg-background text-foreground border-border hover:bg-muted"
              }`}
            >
              {topic}
            </button>
          ))}
        </div>

        {/* Active Synthesized Brief View */}
        {generateMutation.isPending && (
          <div className="p-8 border border-border bg-muted/10 space-y-4">
            <div className="flex items-center gap-3">
              <span className="relative flex h-3 w-3">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-foreground opacity-75"></span>
                <span className="relative inline-flex rounded-full h-3 w-3 bg-foreground"></span>
              </span>
              <span className="font-mono text-xs font-bold uppercase tracking-wider">
                Cross-referencing verified indicators, pulse metrics, and policy signals...
              </span>
            </div>
            <Skeleton className="h-6 w-3/4" />
            <Skeleton className="h-20 w-full" />
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <Skeleton className="h-28 w-full" />
              <Skeleton className="h-28 w-full" />
            </div>
          </div>
        )}

        {activeBrief && !generateMutation.isPending && (
          <div className="border-2 border-foreground p-6 bg-muted/5 space-y-6">
            <div className="flex flex-col md:flex-row md:items-start justify-between gap-4 border-b border-border pb-4">
              <div>
                <div className="flex items-center gap-2 mb-2">
                  <span className={`text-[10px] font-mono font-bold uppercase tracking-wider px-2 py-0.5 ${getOutlookBadge(activeBrief.outlook)}`}>
                    {activeBrief.outlook}
                  </span>
                  {activeBrief.pulse_score && (
                    <span className="text-xs font-mono uppercase tracking-wider text-muted-foreground">
                      Pulse Baseline: <strong className="text-foreground">{activeBrief.pulse_score}/100</strong>
                    </span>
                  )}
                  <span className="text-[10px] font-mono uppercase tracking-wider px-1.5 py-0.5 bg-muted text-muted-foreground border">
                    Verified Grounded
                  </span>
                </div>
                <h3 className="text-2xl font-bold uppercase tracking-tight text-foreground">
                  {activeBrief.title}
                </h3>
                <div className="text-xs font-mono text-muted-foreground mt-1">
                  Focus: {activeBrief.topic}
                </div>
              </div>

              {/* Action Buttons */}
              <div className="flex items-center gap-2 shrink-0">
                <button
                  onClick={() => handleExportMarkdown(activeBrief)}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-mono font-bold uppercase tracking-wider border border-border hover:bg-muted transition-colors"
                >
                  <Download className="w-3.5 h-3.5" />
                  Markdown
                </button>
                <button
                  onClick={() => window.print()}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-mono font-bold uppercase tracking-wider border border-border hover:bg-muted transition-colors"
                >
                  <Printer className="w-3.5 h-3.5" />
                  Print
                </button>
                <button
                  onClick={() => saveMutation.mutate(activeBrief)}
                  disabled={saveMutation.isPending || saveSuccess}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-mono font-bold uppercase tracking-wider bg-foreground text-background hover:bg-muted-foreground transition-colors disabled:opacity-60"
                >
                  {saveSuccess ? (
                    <>
                      <CheckCircle className="w-3.5 h-3.5 text-emerald-400" />
                      Archived
                    </>
                  ) : (
                    <>
                      <BookmarkPlus className="w-3.5 h-3.5" />
                      Save to Archive
                    </>
                  )}
                </button>
              </div>
            </div>

            {/* Executive Summary */}
            <div className="p-4 border-l-4 border-foreground bg-background">
              <h4 className="text-xs font-mono font-bold uppercase tracking-widest text-muted-foreground mb-1">
                Executive Synthesis
              </h4>
              <p className="text-base font-serif leading-relaxed text-foreground">
                {activeBrief.summary}
              </p>
            </div>

            {/* Key Insights & Policy Recommendations */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="p-5 border border-border bg-background">
                <h4 className="text-xs font-mono font-bold uppercase tracking-widest text-foreground mb-3 flex items-center gap-2 border-b pb-2">
                  <TrendingUp className="w-4 h-4 text-foreground" />
                  Empirical Findings & Trends
                </h4>
                <ul className="space-y-2.5">
                  {(activeBrief.key_insights || []).map((insight: string, idx: number) => (
                    <li key={idx} className="text-xs font-serif leading-relaxed text-muted-foreground pl-3 border-l-2 border-border">
                      {insight}
                    </li>
                  ))}
                </ul>
              </div>

              <div className="p-5 border border-border bg-background">
                <h4 className="text-xs font-mono font-bold uppercase tracking-widest text-foreground mb-3 flex items-center gap-2 border-b pb-2">
                  <Scale className="w-4 h-4 text-foreground" />
                  Actionable Policy Prescriptions
                </h4>
                <ul className="space-y-2.5">
                  {(activeBrief.policy_recommendations || []).map((rec: string, idx: number) => (
                    <li key={idx} className="text-xs font-serif leading-relaxed text-foreground pl-3 border-l-2 border-foreground">
                      {rec}
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Downside Risks */}
            {activeBrief.risk_factors && activeBrief.risk_factors.length > 0 && (
              <div className="p-4 border border-destructive/30 bg-destructive/5">
                <h4 className="text-xs font-mono font-bold uppercase tracking-widest text-destructive mb-2 flex items-center gap-2">
                  <AlertCircle className="w-4 h-4 text-destructive" />
                  Identified Downside Vulnerabilities
                </h4>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                  {activeBrief.risk_factors.map((risk: string, idx: number) => (
                    <div key={idx} className="text-xs font-serif text-muted-foreground p-2 border border-destructive/20 bg-background">
                      {risk}
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Published & Saved Research Archive */}
      <div className="space-y-6">
        <div className="border-b-2 border-foreground pb-2 flex items-center justify-between">
          <h2 className="text-xl font-bold uppercase tracking-tight flex items-center gap-2">
            <BookOpen className="w-5 h-5 text-foreground" />
            Published Policy Intelligence Archive
          </h2>
          <span className="font-mono text-xs text-muted-foreground">
            {reports ? `${reports.length} brief(s) archived` : "Loading..."}
          </span>
        </div>

        {reportsLoading ? (
          <div className="space-y-4">
            <Skeleton className="h-36 w-full" />
            <Skeleton className="h-36 w-full" />
          </div>
        ) : reportsError ? (
          <div className="p-8 bg-destructive/10 border border-destructive/20 text-destructive text-center">
            <AlertCircle className="w-8 h-8 mx-auto mb-2" />
            <p className="font-mono text-xs uppercase tracking-wider">Failed to load archived research reports.</p>
          </div>
        ) : reports && reports.length > 0 ? (
          <div className="grid grid-cols-1 gap-6">
            {reports.map((report: any) => (
              <div 
                key={report.id}
                className="border-2 border-foreground bg-background p-6 hover:shadow-md transition-shadow"
              >
                <div className="flex flex-col md:flex-row md:items-start justify-between gap-3 border-b border-border pb-3">
                  <div>
                    <div className="flex items-center gap-2 mb-1.5">
                      <span className={`text-[9px] font-mono font-bold uppercase tracking-wider px-1.5 py-0.5 ${getOutlookBadge(report.outlook)}`}>
                        {report.outlook}
                      </span>
                      <span className="text-xs font-mono text-muted-foreground flex items-center gap-1">
                        <Calendar className="w-3.5 h-3.5" />
                        {new Date(report.created_at).toLocaleDateString(undefined, {
                          year: 'numeric',
                          month: 'short',
                          day: 'numeric'
                        })}
                      </span>
                    </div>
                    <h3 className="text-lg font-bold uppercase tracking-tight text-foreground">
                      {report.title}
                    </h3>
                  </div>

                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => handleExportMarkdown(report)}
                      className="px-2.5 py-1 text-xs font-mono uppercase tracking-wider border border-border hover:bg-muted flex items-center gap-1"
                    >
                      <Download className="w-3 h-3" /> MD
                    </button>
                  </div>
                </div>

                <div className="mt-4 space-y-4">
                  <p className="text-sm font-serif leading-relaxed text-foreground/90">
                    {report.summary}
                  </p>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
                    <div>
                      <h4 className="text-[11px] font-mono font-bold uppercase tracking-wider text-muted-foreground mb-2">
                        Key Empirical Findings
                      </h4>
                      <ul className="space-y-1.5">
                        {(report.insights || []).map((ins: string, i: number) => (
                          <li key={i} className="text-xs font-serif text-muted-foreground pl-2 border-l border-border">
                            {ins}
                          </li>
                        ))}
                      </ul>
                    </div>

                    <div>
                      <h4 className="text-[11px] font-mono font-bold uppercase tracking-wider text-destructive mb-2">
                        Downside Vulnerabilities
                      </h4>
                      <ul className="space-y-1.5">
                        {(report.risk_factors || []).map((risk: string, i: number) => (
                          <li key={i} className="text-xs font-serif text-muted-foreground pl-2 border-l border-destructive/30">
                            {risk}
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="p-12 border-2 border-dashed border-border text-center bg-muted/10">
            <FileText className="w-10 h-10 text-muted-foreground mx-auto mb-3 opacity-40" />
            <h3 className="text-base font-bold uppercase tracking-tight">No Archived Briefs Found</h3>
            <p className="text-xs font-serif text-muted-foreground mt-1 max-w-md mx-auto">
              Select a macroeconomic topic above and click &quot;Generate Brief&quot; to synthesize and archive your first intelligence publication.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
