"""Add provenance metadata

Revision ID: 85aae3b9e59e
Revises: 
Create Date: 2026-09-14 14:09:34.389975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85aae3b9e59e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historical_data', sa.Column('period', sa.String(length=20), nullable=False))
    op.add_column('historical_data', sa.Column('source_checked_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('historical_data', sa.Column('observation_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('historical_data', sa.Column('publication_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('historical_data', sa.Column('native_frequency', sa.String(length=50), nullable=True))
    op.add_column('historical_data', sa.Column('ingestion_time', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('uq_hist_indicator_country_date', 'historical_data', type_='unique')
    op.create_unique_constraint('uq_hist_indicator_country_period', 'historical_data', ['indicator_id', 'country_code', 'period'])
    op.drop_column('historical_data', 'date')
    op.drop_column('historical_data', 'created_at')
    op.add_column('indicators', sa.Column('native_frequency', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indicators', 'native_frequency')
    op.add_column('historical_data', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('historical_data', sa.Column('date', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_hist_indicator_country_period', 'historical_data', type_='unique')
    op.create_unique_constraint('uq_hist_indicator_country_date', 'historical_data', ['indicator_id', 'country_code', 'date'])
    op.drop_column('historical_data', 'ingestion_time')
    op.drop_column('historical_data', 'native_frequency')
    op.drop_column('historical_data', 'publication_time')
    op.drop_column('historical_data', 'observation_time')
    op.drop_column('historical_data', 'source_checked_time')
    op.drop_column('historical_data', 'period')
    # ### end Alembic commands ###
